name: jogo
description: An absolute bare-bones web app.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   logger:
#     path: 'D:\Gabriel\Documents\GitHub\gabrielwbenatti\guia-dart\7-packages\logger'

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.0
